### PR TITLE
Add README.md

### PR DESCRIPTION
**Pull request by kcchik**
Add `README.md` with instructions on how to setup and run the server.

### CODE REVIEW

**Review by Agam642 — APPROVED** [review]
Looks good

**Review by danielkim10 — APPROVED** [review]
Not sure what the pre-commit step does but LGTM

**Comment by Raymond-Xia** [comment]
Had to install a bunch of stuff but works for me

**Review by Raymond-Xia — APPROVED** [review]
Had to install a bunch of stuff but works for me

**Pull request merged**
